

name: cicd pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: avi-webapp   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './build'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x'                # set this to the node version to use

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        
        
    - name: Install Gitleaks
      run: sudo apt install gitleaks
      
    - name: Run Gitleaks Scan
      run: gitleaks detect --source . --report-format json --report-path gitleaks-report.json
      
    - name: Build frontend
      working-directory: frontend
      run: |
        npm install
        npm run build

    - name: Move frontend build to backend public folder
      run: |
        mkdir -p backend/public
        cp -r frontend/dist/* backend/public/

    - name: Install backend dependencies
      working-directory: backend
      run: npm install

    - name: Zip backend for deployment
      run: |
        cd backend
        zip -r ../build.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-zip
        path: build.zip

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: build-zip
        path: .
        
    
          
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: build.zip

          
